TYPE_STAC = "stac"
TYPE_STAC_ITEM = "Feature"
TYPE_STAC_COLLECTION = "Collection"
TYPE_STAC_CATALOG = "Catalog"

TYPE_STAC_RESOURCE = "stac-asset"


SCHEMA_VERSION = 1
SUPPORTED_STAC_RESOURCE_FORMATS = [TYPE_STAC_RESOURCE]
SUPPORTED_DATASET_FORMATS = [TYPE_STAC]
SUPPORTED_INPUT_FORMATS = [TYPE_STAC]