TYPE_STAC = "stac-item"
TYPE_STAC_RESOURCE = "stac-asset"


#TYPE_STAC_ITEM = "stac-item"
#TYPE_STAC_COLLECTION = "stac-collection"
#TYPE_STAC_CATALOG = "stac-catalog"

SCHEMA_VERSION = "1"
SUPPORTED_STAC_RESOURCE_FORMATS = [TYPE_STAC_RESOURCE]
#SUPPORTED_DATASET_FORMATS = [TYPE_STAC_ITEM, TYPE_STAC_COLLECTION, TYPE_STAC_COLLECTION]
SUPPORTED_DATASET_FORMATS = [TYPE_STAC]